#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates MoodCats.xcodeproj from scratch.
#
# The checked-in .xcodeproj is generated by this script rather than hand-edited, so the
# three targets can never drift out of sync on the settings that silently break this app
# -- App Group membership in particular, which Xcode will not warn you about.
#
# Run it any time you add a source file:
#     gem install xcodeproj
#     ruby Tools/generate_xcodeproj.rb
#
# Everything the user is expected to edit lives in Config/Signing.xcconfig, not here.

require 'xcodeproj'
require 'fileutils'

ROOT = File.expand_path('..', __dir__)
PROJECT_PATH = File.join(ROOT, 'MoodCats.xcodeproj')

APP = 'MoodCats'
WIDGET = 'MoodCatsWidget'
NSE = 'MoodCatsNotificationService'

DEPLOYMENT_TARGET = '18.0'
SUPABASE_REPO = 'https://github.com/supabase/supabase-swift.git'
SUPABASE_MIN_VERSION = '2.0.0'

FileUtils.rm_rf(PROJECT_PATH)
project = Xcodeproj::Project.new(PROJECT_PATH)

# ---------------------------------------------------------------------------------------
# Base configuration: Config/Signing.xcconfig drives team id, bundle prefix and App Group.
# ---------------------------------------------------------------------------------------
config_group = project.new_group('Config', 'Config')
xcconfig_ref = config_group.new_reference('Config/Signing.xcconfig')
project.build_configurations.each { |c| c.base_configuration_reference = xcconfig_ref }

# ---------------------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------------------
app = project.new_target(:application, APP, :ios, DEPLOYMENT_TARGET)
widget = project.new_target(:app_extension, WIDGET, :ios, DEPLOYMENT_TARGET)
nse = project.new_target(:app_extension, NSE, :ios, DEPLOYMENT_TARGET)

# ---------------------------------------------------------------------------------------
# Source files
# ---------------------------------------------------------------------------------------

# Compiled into ALL THREE targets. One definition of the data contract, the moods, the
# App Group id and the widget kind -- never duplicated.
SHARED_ALL = %w[
  Shared/Config.swift
  Shared/Mood.swift
  Shared/RosterContract.swift
  Shared/RosterStore.swift
].freeze

# App and widget only. The Notification Service Extension runs under a 24 MB cap and does
# no image work at all, so it does not need (or want) the SwiftUI art layer.
SHARED_UI = %w[Shared/CatArtView.swift].freeze

APP_SOURCES = %w[
  MoodCats/MoodCatsApp.swift
  MoodCats/AppDelegate.swift
  MoodCats/AppModel.swift
  MoodCats/Services/SupabaseService.swift
  MoodCats/Services/NotificationManager.swift
  MoodCats/Services/MoodCatsError.swift
  MoodCats/Views/RootView.swift
  MoodCats/Views/OnboardingView.swift
  MoodCats/Views/GroupChoiceView.swift
  MoodCats/Views/CreateGroupView.swift
  MoodCats/Views/JoinGroupView.swift
  MoodCats/Views/WidgetSetupView.swift
  MoodCats/Views/HomeView.swift
  MoodCats/Views/GroupView.swift
  MoodCats/Views/SettingsView.swift
].freeze

WIDGET_SOURCES = %w[
  MoodCatsWidget/MoodWidget.swift
  MoodCatsWidget/MoodWidgetIntent.swift
  MoodCatsWidget/FriendEntity.swift
  MoodCatsWidget/Views/MoodWidgetView.swift
].freeze

NSE_SOURCES = %w[MoodCatsNotificationService/NotificationService.swift].freeze

# The cat art. Shared by the app and the widget, from a single catalog.
SHARED_RESOURCES = %w[Shared/CatAssets.xcassets].freeze

groups = {}

# Builds (and caches) the group hierarchy mirroring the folder layout on disk.
def group_for(project, groups, path)
  return project.main_group if path.empty?
  return groups[path] if groups[path]

  parent_path = File.dirname(path)
  parent_path = '' if parent_path == '.'
  parent = group_for(project, groups, parent_path)
  groups[path] = parent.new_group(File.basename(path), File.basename(path))
end

def add(project, groups, target, relative_path, resource: false)
  full = File.join(ROOT, relative_path)
  raise "missing file: #{relative_path}" unless File.exist?(full)

  dir = File.dirname(relative_path)
  dir = '' if dir == '.'
  group = group_for(project, groups, dir)

  existing = group.files.find { |f| f.display_name == File.basename(relative_path) }
  ref = existing || group.new_reference(File.basename(relative_path))

  if resource
    target.add_resources([ref])
  else
    target.add_file_references([ref])
  end
  ref
end

SHARED_ALL.each do |path|
  [app, widget, nse].each { |t| add(project, groups, t, path) }
end
SHARED_UI.each do |path|
  [app, widget].each { |t| add(project, groups, t, path) }
end
SHARED_RESOURCES.each do |path|
  [app, widget].each { |t| add(project, groups, t, path, resource: true) }
end

APP_SOURCES.each { |path| add(project, groups, app, path) }
WIDGET_SOURCES.each { |path| add(project, groups, widget, path) }
NSE_SOURCES.each { |path| add(project, groups, nse, path) }

add(project, groups, app, 'MoodCats/Assets.xcassets', resource: true)
add(project, groups, widget, 'MoodCatsWidget/Assets.xcassets', resource: true)

# Info.plist files are referenced (so they show up in the navigator) but never compiled.
[[app, "#{APP}/Info.plist"], [widget, "#{WIDGET}/Info.plist"], [nse, "#{NSE}/Info.plist"]].each do |target, path|
  dir = File.dirname(path)
  group = group_for(project, groups, dir)
  group.new_reference(File.basename(path)) unless group.files.any? { |f| f.display_name == 'Info.plist' }
end

[[app, APP], [widget, WIDGET], [nse, NSE]].each do |_target, name|
  group = group_for(project, groups, name)
  entitlements = "#{name}.entitlements"
  group.new_reference(entitlements) unless group.files.any? { |f| f.display_name == entitlements }
end

# ---------------------------------------------------------------------------------------
# Swift Package: supabase-swift, on the APP TARGET ONLY.
#
# The widget must never make a network request, and the NSE gets its data handed to it in
# the push payload. Neither links this package, which also keeps the extensions small.
# ---------------------------------------------------------------------------------------
package = project.new(Xcodeproj::Project::Object::XCRemoteSwiftPackageReference)
package.repositoryURL = SUPABASE_REPO
package.requirement = { 'kind' => 'upToNextMajorVersion', 'minimumVersion' => SUPABASE_MIN_VERSION }
project.root_object.package_references << package

product = project.new(Xcodeproj::Project::Object::XCSwiftPackageProductDependency)
product.package = package
product.product_name = 'Supabase'
app.package_product_dependencies << product

build_file = project.new(Xcodeproj::Project::Object::PBXBuildFile)
build_file.product_ref = product
app.frameworks_build_phase.files << build_file

# ---------------------------------------------------------------------------------------
# Embed the two extensions in the app, and make them build first.
# ---------------------------------------------------------------------------------------
embed = app.new_copy_files_build_phase('Embed Foundation Extensions')
embed.symbol_dst_subfolder_spec = :plug_ins
embed.dst_path = ''
[widget, nse].each do |extension_target|
  app.add_dependency(extension_target)
  file = embed.add_file_reference(extension_target.product_reference)
  file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }
end

# ---------------------------------------------------------------------------------------
# Build settings
# ---------------------------------------------------------------------------------------
COMMON = {
  'IPHONEOS_DEPLOYMENT_TARGET' => DEPLOYMENT_TARGET,
  'SWIFT_VERSION' => '5.0',
  'TARGETED_DEVICE_FAMILY' => '1',
  'CODE_SIGN_STYLE' => 'Automatic',
  'GENERATE_INFOPLIST_FILE' => 'NO',
  'MARKETING_VERSION' => '1.0',
  'CURRENT_PROJECT_VERSION' => '1',
  'ENABLE_USER_SCRIPT_SANDBOXING' => 'YES',
  'SWIFT_EMIT_LOC_STRINGS' => 'YES',
  'ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME' => 'AccentColor',
  'CLANG_ENABLE_MODULES' => 'YES',
  'ENABLE_PREVIEWS' => 'YES'
}.freeze

PER_TARGET = {
  APP => {
    'PRODUCT_BUNDLE_IDENTIFIER' => '$(BUNDLE_ID_PREFIX).moodcats',
    'INFOPLIST_FILE' => "#{APP}/Info.plist",
    'CODE_SIGN_ENTITLEMENTS' => "#{APP}/#{APP}.entitlements",
    'ASSETCATALOG_COMPILER_APPICON_NAME' => 'AppIcon',
    'PRODUCT_NAME' => 'MoodCats',
    'LD_RUNPATH_SEARCH_PATHS' => '$(inherited) @executable_path/Frameworks'
  },
  WIDGET => {
    'PRODUCT_BUNDLE_IDENTIFIER' => '$(BUNDLE_ID_PREFIX).moodcats.widget',
    'INFOPLIST_FILE' => "#{WIDGET}/Info.plist",
    'CODE_SIGN_ENTITLEMENTS' => "#{WIDGET}/#{WIDGET}.entitlements",
    'ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME' => 'WidgetBackground',
    'SKIP_INSTALL' => 'YES',
    'LD_RUNPATH_SEARCH_PATHS' => '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
  },
  NSE => {
    'PRODUCT_BUNDLE_IDENTIFIER' => '$(BUNDLE_ID_PREFIX).moodcats.notificationservice',
    'INFOPLIST_FILE' => "#{NSE}/Info.plist",
    'CODE_SIGN_ENTITLEMENTS' => "#{NSE}/#{NSE}.entitlements",
    'SKIP_INSTALL' => 'YES',
    'LD_RUNPATH_SEARCH_PATHS' => '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
  }
}.freeze

[[app, APP], [widget, WIDGET], [nse, NSE]].each do |target, name|
  target.build_configurations.each do |configuration|
    settings = configuration.build_settings
    COMMON.each { |k, v| settings[k] = v }
    PER_TARGET[name].each { |k, v| settings[k] = v }

    if configuration.name == 'Debug'
      # What `#if DEBUG` in NotificationManager.apnsEnvironment keys off. A Debug build
      # gets sandbox APNs tokens; Release gets production.
      settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = 'DEBUG $(inherited)'
      settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    else
      settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
    end
  end
end

project.build_configurations.each do |configuration|
  configuration.build_settings['SWIFT_VERSION'] = '5.0'
  configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  configuration.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'NO'
  configuration.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
  configuration.build_settings['SDKROOT'] = 'iphoneos'
end

project.save

# ---------------------------------------------------------------------------------------
# A shared scheme, so the project is runnable the moment it is opened.
# ---------------------------------------------------------------------------------------
scheme = Xcodeproj::XCScheme.new
scheme.add_build_target(app)
scheme.set_launch_target(app)
scheme.save_as(PROJECT_PATH, APP, true)

puts "Generated #{File.basename(PROJECT_PATH)}"
puts "  #{APP}: #{app.source_build_phase.files.count} sources, #{app.resources_build_phase.files.count} resources"
puts "  #{WIDGET}: #{widget.source_build_phase.files.count} sources, #{widget.resources_build_phase.files.count} resources"
puts "  #{NSE}: #{nse.source_build_phase.files.count} sources"
